version: '2'
services: 
    aplicacion: 
        container_name: aplicacion-php
        build:
            context: . 
            dockerfile: Dockerfile-produccion
        ports:
            - "80:80"
        environment:
            DB_USUARIO: aplicacion
            DB_PASSWORD: password
            DB_IP: 192.168.1.10
            DB_NOMBRE: proyecto

    