version: '2'
services: 
    aplicacion: 
        container_name: aplicacion-php
        build:
            context: . 
            dockerfile: Dockerfile-local
        ports:
            - "80:80"
        environment:
            DB_USUARIO: root
            DB_PASSWORD: 1234
            DB_IP: db
            DB_NOMBRE: proyecto
        volumes: 
            - ./:/var/www/html
    db:
        container_name: base-de-datos 
        image: mysql:5.7 
        ports:
            - 3306:3306
        environment: 
            MYSQL_ROOT_PASSWORD: 1234
            MYSQL_DATABASE: proyecto
        volumes:
            - ./mysql:/var/lib/mysql